export const GET_PUBLICATIONS_USER = 'GET_PUBLICATIONS_USER';
export const GET_PUBLICATIONS_USER_LOADING = 'GET_PUBLICATIONS_USER_LOADING';
export const GET_PUBLICATIONS_USER_ERROR = 'GET_PUBLICATIONS_USER_ERROR';
export const GET_FAVORITES_USER = 'GET_FAVORITES_USER';
export const GET_FAVORITES_USER_LOADING = 'GET_FAVORITES_USER_LOADING';
export const GET_FAVORITES_USER_ERROR = 'GET_FAVORITES_USER_ERROR';