export const GET_VEHICLES = "GET_VEHICLES";
export const GET_VEHICLES_LOADING = "GET_VEHICLES_LOADING";
export const GET_VEHICLES_ERROR = "GET_VEHICLES_ERROR";
export const SELECTED_VEHICLE = "SELECTED_VEHICLE";
export const GET_VEHICLE = "GET_VEHICLE";
export const GET_VEHICLE_ERROR = "GET_VEHICLE_ERROR";